name: Absgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.10.11
  - pip
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pymeshlab
  - open3d
  - pip:
    # 使用最新的 PyTorch 支援 RTX 5090
    - torch==2.3.0+cu118 --index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.18.0+cu118 --index-url https://download.pytorch.org/whl/cu118
    - torchaudio==2.3.0+cu118 --index-url https://download.pytorch.org/whl/cu118
    # AbsGS 專用的 CUDA 擴展
    - submodules/diff-gaussian-rasterization-abs
    - submodules/simple-knn
