name: Absgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.10.11
  - pip
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pymeshlab
  - open3d
  - pip:
    - submodules/diff-gaussian-rasterization-abs
    - submodules/simple-knn
